# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'

target 'MKCollectionCircleView' do

pod 'Masonry'

end

